# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sektor BSD
email: n54 [małpa] gmx.com
description: > # this means to ignore newlines until "baseurl:"
  Serwis Sektor BSD powstał pod koniec marca 2015 r. i na ten czas jeszcze jest w fazie rozruchowej. Zamysłem inicjatora strony była aktywizacja polskiego światka BSD, agregacja informacji i przekazywanie ich polskim odbiorcom, popularyzowanie rozwiązań BSD.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://beastie.pl" # the base hostname & protocol for your site
twitter_username: beastiepl
github_username:  beastiepl

# Build settings
markdown: kramdown
